name: Native Image Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Add 'cl.exe' to PATH
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          sdk: 7.1

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: "20.3.0.java8"

      - name: install native image (linux/macos)
        run: gu install native-image
        if: runner.os == 'Linux' || runner.os == 'macOS'

      - name: install native image (windows)
        run: gu.cmd install native-image
        if: runner.os == 'Windows'

      - run: native-image -jar hbs_decipher.jar
        working-directory: target

      - uses: actions/upload-artifact@v2
        with:
          name: hbs_decipher_${{ runner.os }}.zip
          path: target/hbs_decipher*
